"""add created_by to urls

Revision ID: 04ea58b4eee9
Revises: e5d752d7804b
Create Date: 2026-06-05 17:34:48.820760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ea58b4eee9'
down_revision: Union[str, Sequence[str], None] = 'e5d752d7804b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('created_by', sa.String(length=254), nullable=True))
    op.create_index('ix_urls_created_by', 'urls', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_urls_created_by', table_name='urls')
    op.drop_column('urls', 'created_by')
    # ### end Alembic commands ###
