"""add is_blocked to urls

Revision ID: e5d752d7804b
Revises: 0fdaf0c9d906
Create Date: 2026-06-03 15:01:34.011226

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5d752d7804b"
down_revision: Union[str, Sequence[str], None] = "0fdaf0c9d906"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "urls", sa.Column("is_blocked", sa.Boolean(), nullable=False, server_default=text("false"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("urls", "is_blocked")
    # ### end Alembic commands ###
