from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Protocol


@dataclass(frozen=True, slots=True)
class UrlRecord:
    id: int
    original_url: str
    created_at: datetime
    expires_at: datetime
    is_blocked: bool = field(default=False)
    created_by: str | None = field(default=None)
    deleted_at: datetime | None = field(default=None)
    clicks: int = field(default=0)


class IdGenerator(Protocol):
    def next_id(self) -> int: ...


class UrlRepository(Protocol):
    async def insert(self, record: UrlRecord) -> None: ...
    async def find_by_id(self, id: int) -> UrlRecord | None: ...
    async def delete_expired(self) -> None: ...
    async def soft_delete(self, id: int) -> int: ...
    async def delete_soft_deleted_older_than(self, days: int) -> int: ...
    async def find_all_by_created_by(
        self, created_by: str, cursor: int | None, limit: int
    ) -> list[UrlRecord]: ...
    async def update_blocked(self, id: int, blocked: bool) -> int: ...
    async def find_all(self, cursor: int | None, limit: int) -> list[UrlRecord]: ...
    async def increment_clicks(self, id: int) -> None: ...


class CachePort(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl: int) -> None: ...
    async def incr(self, key: str) -> int | None: ...
    async def expire(self, key: str, ttl: int) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def aclose(self) -> None: ...
